apps/iban/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from .views import (
    IBANDetailView, IBANDeleteView, IBANUpdateView, IBANCreateView
)

urlpatterns = [
    # iban add url
    url(r'add/$', IBANCreateView.as_view(), name='iban_create'),
    # iban detail url
    url(r'^(?P<pk>[0-9]+)/$', IBANDetailView.as_view(), name='iban_detail'),
    # iban update url
    url(r'^update/(?P<pk>[0-9]+)/$', IBANUpdateView.as_view(), name='iban_update'),
    # iban delete url
    url(r'^delete/(?P<pk>[0-9]+)/$', IBANDeleteView.as_view(), name='iban_delete'),
]

bank_accounts/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from apps.iban.views import IBANListView

urlpatterns = [
    # Home page
    url(r'^$', IBANListView.as_view(), name='iban_list'),
    url(r'^admin/', admin.site.urls),
    # allauth urls.
    url(r'^accounts/', include('allauth.urls')),
    # iban urls.
    url(r'^iban/', include('apps.iban.urls', namespace='iban')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import uuid

from django.db import models


class AbstractBaseModel(models.Model):
    """
    Base db model with most used fields.

    :uuid `UUIDField`, defines a unique instance uuid version 4.

    :created_at `DateTimeField`, defines instance creation date.

    :updated_at `DateTimeField`, defines instance updating date.

    Example:

    ..  code-block:: python

        from django.db import models
        from apps.core.model import AbstractBaseModel

        class MyNewModel(AbstractBaseModel):
            name = models.CharField(max_length=255)

    """
    uuid = models.UUIDField(default=uuid.uuid4(), editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

apps/iban/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse
from django.utils.encoding import python_2_unicode_compatible
from localflavor.generic.models import IBANField

from apps.core.models import AbstractBaseModel
from .managers import ActiveManager


@python_2_unicode_compatible
class IBANAccount(AbstractBaseModel):
    """
    IBANAccount

    :first_name `CharField` required.

    :las_name `CharField` required.

    :active `BooleanField` required, with True as default,
             only superusers can activate or deactivate the account.

    :created_by `ForeignKey` required, User instance relation.

    :iban `IBANField` required.
    """
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    iban = IBANField(verbose_name='IBAN', use_nordea_extensions=True)

    objects = ActiveManager.as_manager()

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = 'IBAN accounts'

    def __str__(self):
        return '{first_name}, {last_name}'.format(
            first_name=self.first_name, last_name=self.last_name
        )

    def get_absolute_url(self):
        return reverse('iban:iban_detail', kwargs={'pk': self.id})

apps/iban/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import IBANAccount


class IBANAccountModelForm(forms.ModelForm):

    def clean_iban(self):
        """
        Check if IBAN already exist in IBANAccount model.

        :return: ValidationError or cleaned_data['iban']
        """
        iban = self.cleaned_data['iban']
        query_set = self.instance._meta.default_manager.filter(iban=iban)
        if self.instance.pk is not None:
            query_set = query_set.exclude(pk=self.instance.pk)
        if query_set.exists():
            raise ValidationError('IBAN already exist', code='exists')
        return iban

    class Meta:
        model = IBANAccount
        fields = ['first_name', 'last_name', 'iban', ]

apps/iban/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    ListView, DetailView, DeleteView, UpdateView, CreateView
)

from .auth.mixins import PreventManipulationAccessMixin
from .forms import IBANAccountModelForm
from .models import IBANAccount


class IBANBaseViewConfiguration(object):
    """
    The very basic configuration for IBAN Views.
    """
    model = IBANAccount


class IBANBaseListDetailView(LoginRequiredMixin, IBANBaseViewConfiguration):
    """
    Base List and Detail Views, extends `LoginRequiredMixin`
    and `IBANBaseViewConfiguration` to handle authorization
    and base configuration for generic List, Detail Views.
    """

    # use the active manager as the default manager.
    queryset = IBANAccount.objects.active()


class IANBaseCreateUpdateView(IBANBaseViewConfiguration):
    """
    Base Create and Update Views, extends `IBANBaseViewConfiguration`
    """
    template_name = 'ibanaccount_form.html'
    form_class = IBANAccountModelForm

    def form_valid(self, form):
        """
        Assign the form model instance ForeignKey field
        `created_by` with the request.user.

        :param form: ModelForm
        :return: HttpResponseRedirect
        """
        form.instance.created_by = self.request.user
        return super(IANBaseCreateUpdateView, self).form_valid(form)


class IBANBaseCreateView(LoginRequiredMixin, IANBaseCreateUpdateView):
    """
    Base CreateView extends `LoginRequiredMixin` and
    `IANBaseCreateUpdateView` to handle login required
    Authorization and base View configuration.
    """
    pass


class IBANListView(IBANBaseListDetailView, ListView):
    """
    List all `IBANAccount` instances, with 10 pagination
    limit.
    """
    paginate_by = 10
    context_object_name = 'iban_account_list'
    template_name = 'ibanaccount_list.html'


class IBANDetailView(IBANBaseListDetailView, DetailView):
    """
    Detail an `IBANAccount` instance by `pk`.
    """
    context_object_name = 'iban_account_item'
    template_name = 'ibanaccount_detail.html'


class IBANDeleteView(PreventManipulationAccessMixin,
                     IBANBaseViewConfiguration,
                     DeleteView):
    """
    Delete `IBANAccount` View, extends `PreventManipulationAccessMixin`
    `IANBaseCreateUpdateView` and generic `DeleteView`, a restricted
    View that prevent not only Anonymous users but also Authorized
    users who did not create the model instance from performing any
    operation on the model instance.
    """
    success_url = reverse_lazy('iban_list')
    context_object_name = 'iban_account_item'
    template_name = 'ibanaccount_delete.html'


class IBANCreateView(IBANBaseCreateView, CreateView):
    """
    Create a new IBANAccount instance.
    """
    template_name = 'ibanaccount_form_create.html'


class IBANUpdateView(PreventManipulationAccessMixin,
                     IANBaseCreateUpdateView,
                     UpdateView):
    """
    Update `IBANAccount` View, extends `PreventManipulationAccessMixin`
    `IANBaseCreateUpdateView` and generic `UpdateView`, a restricted
    View that prevent not only Anonymous users but also Authorized
    users from performing any operation on the model instance, unless
    it's owned by the request.user.
    """
    template_name = 'ibanaccount_form_update.html'

apps/iban/templates/ibanaccount_delete.html
{% extends 'main.html' %}
{% block head_title %}{% endblock %}
{% block content_wrapper %}
    <div class="col-md-8 col-lg-offset-2">
        <div class="card">
            <h4 class="form_title">Are you sure you want to delete [ {{ iban_account_item.first_name }} ]</h4>
            {% if iban_account_item %}
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover table-striped detail_control">
                        <thead>
                        <tr>
                            <th>First name</th>
                            <th>Last name</th>
                            <th>IBAN</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ iban_account_item.first_name }}</td>
                            <td>{{ iban_account_item.last_name }}</td>
                            <td>{{ iban_account_item.iban }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p class="error col-md-12">No IBAN account found.</p>
            {% endif %}
            {% if request.user == iban_account_item.created_by %}
                <form class="form_instance" method="post">
                    {% csrf_token %}
                    <ul class="form_control nav">
                        {{ form.as_ul }}
                        <input type="submit" value="Delete" class="btn btn-danger btn-fill btn-wd">
                    </ul>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

apps/iban/templates/ibanaccount_detail.html
{% extends 'main.html' %}
{% block head_title %}{{ iban_account_item.first_name }}, {{ iban_account_item.last_name }} | Account{% endblock %}
{% block content_wrapper %}
    <div class="col-md-8 col-lg-offset-2">
        <div class="card">
            <h4 class="form_title">{{ iban_account_item.first_name }} {{ iban_account_item.last_name }} | Account</h4>
            {% if iban_account_item %}
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover table-striped detail_control">
                        <thead>
                        <tr>
                            <th>First name</th>
                            <th>Last name</th>
                            <th>IBAN</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ iban_account_item.first_name }}</td>
                            <td>{{ iban_account_item.last_name }}</td>
                            <td>{{ iban_account_item.iban }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                {% if request.user == iban_account_item.created_by %}

                    {% with iban_account_item.id as id %}
                        <ul class="nav actions_detail">
                            <li class="update"><a class="btn btn-info btn-fill"
                                                  href="{% url 'iban:iban_update' id %}">Update</a>
                            </li>
                            <li class="delete"> <form class="delete_action"
                                              action="{% url 'iban:iban_delete' iban_account_item.id %}" method="post">
                                            {% csrf_token %}
                                            <input class="delete btn btn-danger btn-fill" type="submit" value="Delete"/>
                                        </form></li>
                        </ul>
                    {% endwith %}

                {% endif %}
            {% else %}
                <p class="error col-md-12">No IBAN account found.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

apps/iban/templates/ibanaccount_form.html
{% extends 'main.html' %}
{% block head_title %}{% if title %}{{ title }}{% else %}Add or Update{% endif %}{% endblock %}
{% block content_wrapper %}
    <div class="col-md-8 col-lg-offset-2">
        <div class="card">
            <h4 class="form_title">{% if title %}{{ title }}{% else %}Add or Update{% endif %}</h4>
            <form class="form_instance" method="post" action="{{ action }}">
                {% csrf_token %}
                <ul class="form_control nav">
                    {{ form.as_ul }}
                    <input type="submit" value="submit" class="btn btn-info btn-fill btn-wd">
                </ul>
            </form>
        </div>
    </div>

{% endblock %}

apps/iban/templates/ibanaccount_form_create.html
{% extends 'main.html' %}
{% block head_title %}Create a new user{% endblock %}
{% block content_wrapper %}
    <div class="col-md-8 col-lg-offset-2">
        <div class="card">
            <h4 class="form_title">Create a new user</h4>
            <form class="form_instance" method="post" action="{{ action }}">
                {% csrf_token %}
                <ul class="form_control nav">
                    {{ form.as_ul }}
                    <input type="submit" value="submit" class="btn btn-info btn-fill btn-wd">
                </ul>
            </form>
        </div>
    </div>
{% endblock %}

apps/iban/templates/ibanaccount_form_update.html
{% extends 'main.html' %}
{% block head_title %}Update {{ object.first_name }} {{ object.last_name }}{% endblock %}
{% block content_wrapper %}

    <div class="col-md-8 col-lg-offset-2">
        <div class="card">
            {% comment %}
            Another security layer to prevent reaching and updating the instance
            unless the object.create_by == request.user
            {% endcomment %}
            {% if object.created_by == request.user %}
            <h4 class="form_title">Update an existence user</h4>
                <form class="form_instance" method="post" action="{{ action }}">
                    {% csrf_token %}
                    <ul class="form_control nav">
                        {{ form.as_ul }}
                        <input type="submit" value="submit" class="btn btn-info btn-fill btn-wd">
                    </ul>
                </form>
                </div>
            {% else %}
                <p class="warning">You shouldn't be here anyway</p>
            {% endif %}
    </div>
{% endblock %}

apps/iban/templates/ibanaccount_list.html
{% extends 'main.html' %}
{% load iban_tmp %}
{% block head_title %}Home{% endblock %}
{% block content_wrapper %}
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">IBAN List</h4>
                <p class="category">List of all active accounts.</p>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                    <thead>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>IBAN</th>
                    <th class="country_code">Country Code</th>
                    <th></th>
                    </thead>
                    <tbody>
                    {% for iban_account_item in iban_account_list %}
                        <tr>
                            <td>
                                <a href="{% url 'iban:iban_detail' iban_account_item.id %} ">{{ iban_account_item.id }}</a>
                            </td>
                            <td>{{ iban_account_item.first_name }}</td>
                            <td>{{ iban_account_item.last_name }}</td>
                            <td>{{ iban_account_item.iban }}</td>
                            {% if iban_account_item.iban|iban_country_code %}
                                <td class="country_code">{{ iban_account_item.iban|iban_country_code }}</td>
                            {% endif %}
                            {% if request.user == iban_account_item.created_by %}
                                {% with iban_account_item.id as id %}
                                    <td class="actions">
                                        <a class="btn btn-primary update"
                                           href="{% url 'iban:iban_update' id %}">Update</a>
                                        <form class="delete_action"
                                              action="{% url 'iban:iban_delete' iban_account_item.id %}" method="post">
                                            {% csrf_token %}
                                            <input class="delete btn btn-danger" type="submit" value="Delete"/>
                                        </form>

                                    </td>
                                {% endwith %}
                            {% endif %}
                        </tr>
                    {% empty %}
                        <div class="col-md-12"><p class="error">No IBAN accounts found.</p></div>
                    {% endfor %}
                    </tbody>
                </table>
                <ul class="pagination col-md-12 pagination-lg">
                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            </div>
        </div>

    </div>
{% endblock %}

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}{% endblock %}
{% block extra_head %}
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>
    <meta name="viewport" content="width=device-width"/>
    <meta charset="utf-8"/>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>

    {% block css %}
        <!-- Animation library for notifications   -->
        <link href="{% static 'css/animate.min.css' %}" rel="stylesheet"/>

        <!--  Light Bootstrap Table core CSS    -->
        <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet"/>

        <!--     Fonts and icons     -->
        <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
        <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet"/>

    {% endblock %}
    {% block custom_css %}
        <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    {% endblock %}
{% endblock %}
<body>
{% block body %}
    <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="{% static 'img/sidebar-5.jpg' %}">

            <div class="sidebar-wrapper">
                <div class="logo">
                    <span class="simple-text">
                        Welcome <span>{{ request.user.username }}</span>
                    </span>
                </div>

                <ul class="nav">
                    <li class="active">
                        <a href="{% url 'iban_list' %}">
                            <i class="pe-7s-graph"></i>
                            <p>IBAN users List</p>
                        </a>
                    </li>

                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'iban_list' %}">Dashboard</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-left">
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-dashboard"></i>
                                </a>
                            </li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a class="btn btn-info btn-fill btn-wd" href="{% url 'iban:iban_create' %}">
                                    <span>Add User IBAN</span></a>
                            </li>
                            <li>
                                <form class="logout" method="post" action="{% url 'account_logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-fill btn-danger">Log Out</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>


            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        {% block content_wrapper %}
                        {% endblock %}
                    </div>
                </div>
            </div>


            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="{% url 'iban_list' %}">
                                    Home
                                </a>
                            </li>

                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy;
                        <script>document.write(new Date().getFullYear())</script>
                    </p>
                </div>
            </footer>

        </div>
    </div>
    {% block customjs %}
        <!--   Core JS Files   -->
        <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
        <!--  Charts Plugin -->
        <script src="{% static 'js/chartist.min.js' %}"></script>
        <!--  Notifications Plugin    -->
        <script src="{% static 'js/bootstrap-notify.js' %}"></script>
        <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
        <script src="{% static 'js/light-bootstrap-dashboard.js' %}"></script>

    {% endblock %}
{% endblock %}